#!/usr/bin/env bash
#  a Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

for (( count=1; count <= 100; count++))
do
	if [[ $((count % 3)) -eq 0 && $((count % 5)) -eq 0 ]]; then
		echo "FizzBuzz"
	elif [[ $((count % 3)) -eq 0 ]]; then
		echo "Fizz"
	elif [[ $((count % 5)) -eq 0 ]]; then
		echo "Buzz"
	else
		echo "$count"
	fi
done
