#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

Hour=0
while [ $Hour -le 12 ]
do
	echo "Hour: $Hour"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		minutes=$((minutes + 1))
	done
	Hour=$((Hour + 1))
done
