#!/usr/bin/env bash
# A Bash script to configure custom hostname resolution on Ubuntu.


# Backup the original /etc/hosts file
cp /etc/hosts /etc/hosts.bak

sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' /etc/hosts
