#!/usr/bin/env bash
# A Bash script that displays all active IPv4 IPs on the machine, excluding docker and virtual interfaces

ip -o -4 addr show scope global | awk '{print $4}' | cut -d/ -f1
ip -o -4 addr show scope host | awk '{print $4}' | cut -d/ -f1

